using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    //‰ñ“]‘¬“x
    public float rotationSpeed = 1f;
    //x²‰ñ“]Šp“x‚ÌÅ‘å’l
    public float max_rotation_x = 60f;
    //Œ»İ‚Ì‰ñ“]Šp“x
    private float rotation_x = 0f;
    private float rotation_y = 0f;

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKey(KeyCode.LeftArrow))
        {
            //‰ñ“]Šp“x‚ğ•ÏX
            rotation_y -= rotationSpeed;
            //y²‚ğ²‚É¶‰ñ‚è‚ÉrotationSpeed“x‰ñ“]
            transform.rotation = Quaternion.Euler(rotation_x, rotation_y, 0);
        }
        else if (Input.GetKey(KeyCode.RightArrow))
        {
            //‰ñ“]Šp“x‚ğ•ÏX
            rotation_y += rotationSpeed;
            //y²‚ğ²‚É¶‰ñ‚è‚ÉrotationSpeed“x‰ñ“]
            transform.rotation = Quaternion.Euler(rotation_x, rotation_y, 0);
        }
        else if (Input.GetKey(KeyCode.UpArrow))
        {
            //ƒJƒƒ‰‚Ìc•ûŒü‚ÌŠp“x‚Ì”ÍˆÍ‚ğw’è
            if (rotation_x < -max_rotation_x)
            {
                //”ÍˆÍŠO‚Ì‚Æ‚«return
                return;
            }
            //‰ñ“]Šp“x‚ğ•ÏX
            rotation_x -= rotationSpeed;
            //x²‚ğ²‚Éã•ûŒü‚É‰ñ“]
            transform.rotation = Quaternion.Euler(rotation_x, rotation_y, 0);
        }
        else if (Input.GetKey(KeyCode.DownArrow))
        {
            //ƒJƒƒ‰‚Ìc•ûŒü‚ÌŠp“x‚Ì”ÍˆÍ‚ğw’è
            if (rotation_x > max_rotation_x)
            {
                //”ÍˆÍŠO‚Ì‚Æ‚«return
                return;
            }
            //‰ñ“]Šp“x‚ğ•ÏX
            rotation_x += rotationSpeed;
            //x²‚ğ²‚Éã•ûŒü‚É‰ñ“]
            transform.rotation = Quaternion.Euler(rotation_x, rotation_y, 0);
        }
    }
}